config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  resources :users, only: [:new, :create] do
    resources :weathers, only: [:index, :show, :create]
  end
  resources :sessions, only: [:new, :create]
  delete '/logout', to: 'sessions#destroy', as: :logout

  namespace :api do
    get 'user', to: 'users#show'
    get 'user/update', to: 'users#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true
  has_many :weathers
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :user
  validates :name, :temps, :pressure, :humidities, :lon, :lat, presence: true
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  # before_action -> { doorkeeper_authorize! :public }, only: :show
  # before_action -> { doorkeeper_authorize! :write }, only: :update

  def show
    # render json: current_resource_owner.as_json
    response = JSON.parse RestClient.get('http://api.openweathermap.org/data/2.5/forecast?appid=d6ae301398cd22a6c44139eaaf95c03a&q=fastov,ukraine')
    # render response
    render json: response
  end

  def update
    render json: { result: current_resource_owner.touch(:updated_at) }
  end

  private

  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    @weathers = Weather.where(user_id: params[:id])
    render json: @weathers
  end

  def show
    # @weather = Weather.where(user_id: params[:id]).first

    render json: params
  end

  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def doorkeeper_unauthorized_render_options(error: nil)
    { json: { error: "Not authorized" } }
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
      flash[:warning] = "You have entered incorrect email and/or password."
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/weathers_controller.rb
  class WeathersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    # looks for weathers list of chosen user
    @weathers = Weather.where(user_id: params[:user_id])

    # renders serialized info about the weather list
    render json: @weathers
  end

  def show
    # looks for weather from weathers list for current user
    @weather = Weather.where(user_id: params[:user_id], id: params[:id])

    # render serialized info about this weather
    render json: @weather
  end

  def create
    # url that fetches data from openweathermap API
    request_url = 'http://api.openweathermap.org/data/2.5/forecast?appid=d6ae301398cd22a6c44139eaaf95c03a&q=fastov,ukraine'

    # parses data that contains the all info about city and weather in this city
    response = JSON.parse RestClient.get(request_url)

    # city's info
    city_lon = response['city']['coord']['lon'].to_json
    city_lat = response['city']['coord']['lat'].to_json
    city_name = response['city']['name'].to_json

    # weather's info
    weather_temps = response['list'][0]['main']['temp'].to_json
    weather_pressure = response['list'][0]['main']['pressure'].to_json
    weather_humidity = response['list'][0]['main']['humidity'].to_json

    # user id
    user_id = params[:user_id]

    # creates record with appropriate data about weather in the chosen city
    errors = Array.new

    # pushes error if city is already in list
    city_in_list = Weather.where(user_id: user_id, name: city_name).first
    errors.push('This city already in list') if city_in_list

     @weather = Weather.new(
        name: city_name,
        temps: weather_temps,
        pressure: weather_pressure,
        humidities: weather_humidity,
        lon: city_lon,
        lat: city_lat,
        user_id: user_id
    )

    # saves record to db if errors weren't founded
    errors.empty? && @weather.save

    # renders the data about created record
    render json: errors.empty? ? @weather : { errors: errors}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoorkeeperAppExample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
    You are logged in as <%= current_user.email %><br>
    <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
    <%= link_to 'Log In', new_session_path %><br>
    <%= link_to 'Register', new_user_path %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div>
      <h5>Some errors were found:</h5>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>
    <%= render 'shared/errors', object: @user %>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit %>
<% end %>

<%= link_to 'Log In', new_session_path %>